"""add_13_new_fields_to_invoice_and_change_status_default

Revision ID: 841bfb32250c
Revises: 5af32c995c03
Create Date: 2026-05-16 13:35:15.946873
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '841bfb32250c'
down_revision: Union[str, None] = '5af32c995c03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('file_original_name', sa.String(length=255), nullable=True))
    op.add_column('invoices', sa.Column('buyer_name', sa.String(length=200), nullable=True))
    op.add_column('invoices', sa.Column('invoice_type', sa.String(length=100), nullable=True))
    op.add_column('invoices', sa.Column('project_name', sa.String(length=200), nullable=True))
    op.add_column('invoices', sa.Column('train_no', sa.String(length=50), nullable=True))
    op.add_column('invoices', sa.Column('departure_station', sa.String(length=100), nullable=True))
    op.add_column('invoices', sa.Column('arrival_station', sa.String(length=100), nullable=True))
    op.add_column('invoices', sa.Column('departure_location', sa.String(length=200), nullable=True))
    op.add_column('invoices', sa.Column('arrival_location', sa.String(length=200), nullable=True))
    op.add_column('invoices', sa.Column('flight_no', sa.String(length=50), nullable=True))
    op.add_column('invoices', sa.Column('departure_city', sa.String(length=100), nullable=True))
    op.add_column('invoices', sa.Column('arrival_city', sa.String(length=100), nullable=True))
    op.add_column('invoices', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'deleted_at')
    op.drop_column('invoices', 'arrival_city')
    op.drop_column('invoices', 'departure_city')
    op.drop_column('invoices', 'flight_no')
    op.drop_column('invoices', 'arrival_location')
    op.drop_column('invoices', 'departure_location')
    op.drop_column('invoices', 'arrival_station')
    op.drop_column('invoices', 'departure_station')
    op.drop_column('invoices', 'train_no')
    op.drop_column('invoices', 'project_name')
    op.drop_column('invoices', 'invoice_type')
    op.drop_column('invoices', 'buyer_name')
    op.drop_column('invoices', 'file_original_name')
    # ### end Alembic commands ###
